import { allCountries } from "country-telephone-data";


export const assetCategories = [
  "Real Estate",
  "Commodities",
  "Company Equity",
  "Art & Collectibles",
  "Intellectual Property",
  "Other",
];

export const countries = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Portugal",
  "Ireland",
  "Greece",
  "Czech Republic",
  "Romania",
  "Hungary",
  "Bulgaria",
  "Croatia",
  "Slovakia",
  "Slovenia",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Luxembourg",
  "Malta",
  "Cyprus",
  "Japan",
  "China",
  "India",
  "South Korea",
  "Singapore",
  "Hong Kong",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Taiwan",
  "New Zealand",
  "South Africa",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "UAE",
  "Saudi Arabia",
  "Israel",
  "Turkey",
  "Russia",
  "Ukraine",
  "Egypt",
  "Nigeria",
  "Kenya",
  "Ghana",
  "Morocco",
  "Tunisia",
  "Algeria",
  "Other",
];

export const countryCodeToName: Record<string, string> = {
  IND: "India",
  USA: "United States",
  GBR: "United Kingdom",
  CAN: "Canada",
  AUS: "Australia",
  DEU: "Germany",
  FRA: "France",
  ITA: "Italy",
  ESP: "Spain",
  NLD: "Netherlands",
  BEL: "Belgium",
  CHE: "Switzerland",
  AUT: "Austria",
  SWE: "Sweden",
  NOR: "Norway",
  DNK: "Denmark",
  FIN: "Finland",
  POL: "Poland",
  PRT: "Portugal",
  IRL: "Ireland",
  GRC: "Greece",
  CZE: "Czech Republic",
  ROU: "Romania",
  HUN: "Hungary",
  BGR: "Bulgaria",
  HRV: "Croatia",
  SVK: "Slovakia",
  SVN: "Slovenia",
  LTU: "Lithuania",
  LVA: "Latvia",
  EST: "Estonia",
  LUX: "Luxembourg",
  MLT: "Malta",
  CYP: "Cyprus",
  JPN: "Japan",
  CHN: "China",
  KOR: "South Korea",
  SGP: "Singapore",
  MYS: "Malaysia",
  THA: "Thailand",
  IDN: "Indonesia",
  PHL: "Philippines",
  VNM: "Vietnam",
  TWN: "Taiwan",
  NZL: "New Zealand",
  ZAF: "South Africa",
  BRA: "Brazil",
  MEX: "Mexico",
  ARG: "Argentina",
  CHL: "Chile",
  COL: "Colombia",
  PER: "Peru",
  ARE: "UAE",
  SAU: "Saudi Arabia",
  ISR: "Israel",
  TUR: "Turkey",
  RUS: "Russia",
  UKR: "Ukraine",
  EGY: "Egypt",
  NGA: "Nigeria",
  KEN: "Kenya",
  GHA: "Ghana",
  MAR: "Morocco",
  TUN: "Tunisia",
  DZA: "Algeria",
};

export const countryCodes = [
  { code: "+1", country: "USA/Canada", flag: "🇺🇸" },
  { code: "+7", country: "Russia", flag: "🇷🇺" },
  { code: "+20", country: "Egypt", flag: "🇪🇬" },
  { code: "+27", country: "South Africa", flag: "🇿🇦" },
  { code: "+30", country: "Greece", flag: "🇬🇷" },
  { code: "+31", country: "Netherlands", flag: "🇳🇱" },
  { code: "+32", country: "Belgium", flag: "🇧🇪" },
  { code: "+33", country: "France", flag: "🇫🇷" },
  { code: "+34", country: "Spain", flag: "🇪🇸" },
  { code: "+36", country: "Hungary", flag: "🇭🇺" },
  { code: "+39", country: "Italy", flag: "🇮🇹" },
  { code: "+40", country: "Romania", flag: "🇷🇴" },
  { code: "+41", country: "Switzerland", flag: "🇨🇭" },
  { code: "+43", country: "Austria", flag: "🇦🇹" },
  { code: "+44", country: "United Kingdom", flag: "🇬🇧" },
  { code: "+45", country: "Denmark", flag: "🇩🇰" },
  { code: "+46", country: "Sweden", flag: "🇸🇪" },
  { code: "+47", country: "Norway", flag: "🇳🇴" },
  { code: "+48", country: "Poland", flag: "🇵🇱" },
  { code: "+49", country: "Germany", flag: "🇩🇪" },
  { code: "+51", country: "Peru", flag: "🇵🇪" },
  { code: "+52", country: "Mexico", flag: "🇲🇽" },
  { code: "+53", country: "Cuba", flag: "🇨🇺" },
  { code: "+54", country: "Argentina", flag: "🇦🇷" },
  { code: "+55", country: "Brazil", flag: "🇧🇷" },
  { code: "+56", country: "Chile", flag: "🇨🇱" },
  { code: "+57", country: "Colombia", flag: "🇨🇴" },
  { code: "+58", country: "Venezuela", flag: "🇻🇪" },
  { code: "+60", country: "Malaysia", flag: "🇲🇾" },
  { code: "+61", country: "Australia", flag: "🇦🇺" },
  { code: "+62", country: "Indonesia", flag: "🇮🇩" },
  { code: "+63", country: "Philippines", flag: "🇵🇭" },
  { code: "+64", country: "New Zealand", flag: "🇳🇿" },
  { code: "+65", country: "Singapore", flag: "🇸🇬" },
  { code: "+66", country: "Thailand", flag: "🇹🇭" },
  { code: "+81", country: "Japan", flag: "🇯🇵" },
  { code: "+82", country: "South Korea", flag: "🇰🇷" },
  { code: "+84", country: "Vietnam", flag: "🇻🇳" },
  { code: "+86", country: "China", flag: "🇨🇳" },
  { code: "+90", country: "Turkey", flag: "🇹🇷" },
  { code: "+91", country: "India", flag: "🇮🇳" },
  { code: "+92", country: "Pakistan", flag: "🇵🇰" },
  { code: "+93", country: "Afghanistan", flag: "🇦🇫" },
  { code: "+94", country: "Sri Lanka", flag: "🇱🇰" },
  { code: "+95", country: "Myanmar", flag: "🇲🇲" },
  { code: "+98", country: "Iran", flag: "🇮🇷" },
  { code: "+212", country: "Morocco", flag: "🇲🇦" },
  { code: "+213", country: "Algeria", flag: "🇩🇿" },
  { code: "+216", country: "Tunisia", flag: "🇹🇳" },
  { code: "+218", country: "Libya", flag: "🇱🇾" },
  { code: "+220", country: "Gambia", flag: "🇬🇲" },
  { code: "+221", country: "Senegal", flag: "🇸🇳" },
  { code: "+234", country: "Nigeria", flag: "🇳🇬" },
  { code: "+254", country: "Kenya", flag: "🇰🇪" },
  { code: "+255", country: "Tanzania", flag: "🇹🇿" },
  { code: "+256", country: "Uganda", flag: "🇺🇬" },
  { code: "+260", country: "Zambia", flag: "🇿🇲" },
  { code: "+263", country: "Zimbabwe", flag: "🇿🇼" },
  { code: "+351", country: "Portugal", flag: "🇵🇹" },
  { code: "+352", country: "Luxembourg", flag: "🇱🇺" },
  { code: "+353", country: "Ireland", flag: "🇮🇪" },
  { code: "+354", country: "Iceland", flag: "🇮🇸" },
  { code: "+358", country: "Finland", flag: "🇫🇮" },
  { code: "+370", country: "Lithuania", flag: "🇱🇹" },
  { code: "+371", country: "Latvia", flag: "🇱🇻" },
  { code: "+372", country: "Estonia", flag: "🇪🇪" },
  { code: "+380", country: "Ukraine", flag: "🇺🇦" },
  { code: "+381", country: "Serbia", flag: "🇷🇸" },
  { code: "+385", country: "Croatia", flag: "🇭🇷" },
  { code: "+386", country: "Slovenia", flag: "🇸🇮" },
  { code: "+420", country: "Czech Republic", flag: "🇨🇿" },
  { code: "+421", country: "Slovakia", flag: "🇸🇰" },
  { code: "+423", country: "Liechtenstein", flag: "🇱🇮" },
  { code: "+852", country: "Hong Kong", flag: "🇭🇰" },
  { code: "+853", country: "Macau", flag: "🇲🇴" },
  { code: "+855", country: "Cambodia", flag: "🇰🇭" },
  { code: "+856", country: "Laos", flag: "🇱🇦" },
  { code: "+880", country: "Bangladesh", flag: "🇧🇩" },
  { code: "+886", country: "Taiwan", flag: "🇹🇼" },
  { code: "+960", country: "Maldives", flag: "🇲🇻" },
  { code: "+961", country: "Lebanon", flag: "🇱🇧" },
  { code: "+962", country: "Jordan", flag: "🇯🇴" },
  { code: "+963", country: "Syria", flag: "🇸🇾" },
  { code: "+964", country: "Iraq", flag: "🇮🇶" },
  { code: "+965", country: "Kuwait", flag: "🇰🇼" },
  { code: "+966", country: "Saudi Arabia", flag: "🇸🇦" },
  { code: "+967", country: "Yemen", flag: "🇾🇪" },
  { code: "+968", country: "Oman", flag: "🇴🇲" },
  { code: "+971", country: "UAE", flag: "🇦🇪" },
  { code: "+972", country: "Israel", flag: "🇮🇱" },
  { code: "+973", country: "Bahrain", flag: "🇧🇭" },
  { code: "+974", country: "Qatar", flag: "🇶🇦" },
  { code: "+975", country: "Bhutan", flag: "🇧🇹" },
  { code: "+976", country: "Mongolia", flag: "🇲🇳" },
  { code: "+977", country: "Nepal", flag: "🇳🇵" },
  { code: "+992", country: "Tajikistan", flag: "🇹🇯" },
  { code: "+993", country: "Turkmenistan", flag: "🇹🇲" },
  { code: "+994", country: "Azerbaijan", flag: "🇦🇿" },
  { code: "+995", country: "Georgia", flag: "🇬🇪" },
  { code: "+996", country: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "+998", country: "Uzbekistan", flag: "🇺🇿" },
];

export const phoneRegex = /^[0-9]{7,15}$/;


export const iso3ToDialCode: Record<string, string> = {
  USA: "+1", CAN: "+1", RUS: "+7", EGY: "+20", ZAF: "+27",
  GRC: "+30", NLD: "+31", BEL: "+32", FRA: "+33", ESP: "+34",
  HUN: "+36", ITA: "+39", ROU: "+40", CHE: "+41", AUT: "+43",
  GBR: "+44", DNK: "+45", SWE: "+46", NOR: "+47", POL: "+48",
  DEU: "+49", PER: "+51", MEX: "+52", CUB: "+53", ARG: "+54",
  BRA: "+55", CHL: "+56", COL: "+57", VEN: "+58", MYS: "+60",
  AUS: "+61", IDN: "+62", PHL: "+63", NZL: "+64", SGP: "+65",
  THA: "+66", JPN: "+81", KOR: "+82", VNM: "+84", CHN: "+86",
  TUR: "+90", IND: "+91", PAK: "+92", AFG: "+93", LKA: "+94",
  MMR: "+95", IRN: "+98", MAR: "+212", DZA: "+213", TUN: "+216",
  LBY: "+218", GMB: "+220", SEN: "+221", NGA: "+234", KEN: "+254",
  TZA: "+255", UGA: "+256", ZMB: "+260", ZWE: "+263", PRT: "+351",
  LUX: "+352", IRL: "+353", ISL: "+354", FIN: "+358", LTU: "+370",
  LVA: "+371", EST: "+372", UKR: "+380", SRB: "+381", HRV: "+385",
  SVN: "+386", CZE: "+420", SVK: "+421", LIE: "+423", HKG: "+852",
  MAC: "+853", KHM: "+855", LAO: "+856", BGD: "+880", TWN: "+886",
  MDV: "+960", LBN: "+961", JOR: "+962", SYR: "+963", IRQ: "+964",
  KWT: "+965", SAU: "+966", YEM: "+967", OMN: "+968", ARE: "+971",
  ISR: "+972", BHR: "+973", QAT: "+974", BTN: "+975", MNG: "+976",
  NPL: "+977", TJK: "+992", TKM: "+993", AZE: "+994", GEO: "+995",
  KGZ: "+996", UZB: "+998",
};

export const getDialCodeFromIso3 = (iso3: string): string => {
  return iso3ToDialCode[iso3?.toUpperCase()] ?? "";
};

// export const countryOptions = allCountries.map((c) => ({
//   label: `${c.name} (+${c.dialCode})`,
//   value: `+${c.dialCode}`,
//   iso2: c.iso2.toUpperCase(),
// }));
// export function getFlagEmoji(countryCode: string) {
//   return countryCode
//     .toUpperCase()
//     .replace(/./g, char =>
//       String.fromCodePoint(127397 + char.charCodeAt(0))
//     );
// }