export const assetCategories = [
  "Real Estate",
  "Commodities",
  "Company Equity",
  "Art & Collectibles",
  "Intellectual Property",
  "Other",
];

export const countries = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Portugal",
  "Ireland",
  "Greece",
  "Czech Republic",
  "Romania",
  "Hungary",
  "Bulgaria",
  "Croatia",
  "Slovakia",
  "Slovenia",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Luxembourg",
  "Malta",
  "Cyprus",
  "Japan",
  "China",
  "India",
  "South Korea",
  "Singapore",
  "Hong Kong",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Taiwan",
  "New Zealand",
  "South Africa",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "UAE",
  "Saudi Arabia",
  "Israel",
  "Turkey",
  "Russia",
  "Ukraine",
  "Egypt",
  "Nigeria",
  "Kenya",
  "Ghana",
  "Morocco",
  "Tunisia",
  "Algeria",
  "Other",
];

export const countryCodeToName: Record<string, string> = {
  IND: "India",
  USA: "United States",
  GBR: "United Kingdom",
  CAN: "Canada",
  AUS: "Australia",
  DEU: "Germany",
  FRA: "France",
  ITA: "Italy",
  ESP: "Spain",
  NLD: "Netherlands",
  BEL: "Belgium",
  CHE: "Switzerland",
  AUT: "Austria",
  SWE: "Sweden",
  NOR: "Norway",
  DNK: "Denmark",
  FIN: "Finland",
  POL: "Poland",
  PRT: "Portugal",
  IRL: "Ireland",
  GRC: "Greece",
  CZE: "Czech Republic",
  ROU: "Romania",
  HUN: "Hungary",
  BGR: "Bulgaria",
  HRV: "Croatia",
  SVK: "Slovakia",
  SVN: "Slovenia",
  LTU: "Lithuania",
  LVA: "Latvia",
  EST: "Estonia",
  LUX: "Luxembourg",
  MLT: "Malta",
  CYP: "Cyprus",
  JPN: "Japan",
  CHN: "China",
  KOR: "South Korea",
  SGP: "Singapore",
  MYS: "Malaysia",
  THA: "Thailand",
  IDN: "Indonesia",
  PHL: "Philippines",
  VNM: "Vietnam",
  TWN: "Taiwan",
  NZL: "New Zealand",
  ZAF: "South Africa",
  BRA: "Brazil",
  MEX: "Mexico",
  ARG: "Argentina",
  CHL: "Chile",
  COL: "Colombia",
  PER: "Peru",
  ARE: "UAE",
  SAU: "Saudi Arabia",
  ISR: "Israel",
  TUR: "Turkey",
  RUS: "Russia",
  UKR: "Ukraine",
  EGY: "Egypt",
  NGA: "Nigeria",
  KEN: "Kenya",
  GHA: "Ghana",
  MAR: "Morocco",
  TUN: "Tunisia",
  DZA: "Algeria",
};

export const countryCodes = [
  { code: "+1", country: "US/CA", flag: "🇺🇸" },
  { code: "+44", country: "UK", flag: "🇬🇧" },
  { code: "+212", country: "MA", flag: "🇲🇦" },
  { code: "+91", country: "IND", flag: "🇮🇳" },
];

export const phoneRegex = /^[0-9]{7,15}$/;
